# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevnik',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Rasp'),
        ),
    ]
