# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190528_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='_s1',
            new_name='s1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s2',
            new_name='s2',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s3',
            new_name='s3',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s4',
            new_name='s4',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s5',
            new_name='s5',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s6',
            new_name='s6',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s7',
            new_name='s7',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='_s8',
            new_name='s8',
        ),
    ]
