# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190531_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnevnik',
            old_name='comment1',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='dnevnik',
            old_name='value1',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment3',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment4',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment5',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment6',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment7',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='comment8',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value6',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value7',
        ),
        migrations.RemoveField(
            model_name='dnevnik',
            name='value8',
        ),
        migrations.AddField(
            model_name='dnevnik',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.Rasp'),
        ),
    ]
