# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Django_pr/static/profile_img'),
        ),
    ]
